### ISSUE TITLE
QUERY not working

### ISSUE THREAD

**Issue by BPplays** [6jarjar6/nordlynx#22]
### **Describe the bug**
using QUERY in the environment variables does not work, it just ignores what i put and chooses whatever server it wants, but the same option works with curl:
```bash
curl --silent "https://api.nordvpn.com/v1/servers/recommendations?filters\[servers_technologies\]\[identifier\]=openvpn_udp_v6" | jq
```

### **To Reproduce using docker-compose**
docker-compose.yml if used  (hide credentials)
```yaml
services:
  vpn:
    image: ghcr.io/6jarjar6/nordlynx:latest
    container_name: nordvpn_qbittorrent
    
    network_mode: bridge
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required

    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - NET6_LOCAL=fdac:f190:a948::/64
      - NET_LOCAL=192.168.1.0/24
      - ALLOWED_IPS=::/0,0.0.0.0/0
      - PRIVATE_KEY=censored
      - QUERY=filters\[servers_technologies\]\[identifier\]=openvpn_udp_v6

    ports:
      - 50024:50024
      - 50023:50023
      - 50023:50023/udp
      - 50022:50022
      - 50022:50022/udp
      - 25100:25100
      - 28080:28080

      - 50124:50124
      - 50123:50123
      - 50123:50123/udp
      - 50122:50122
      - 50122:50122/udp
      - 25200:25200
      - 28081:28081
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0  # Recomended if using ipv4 only
    restart: always
    extra_hosts:
    - "host.docker.internal:host-gateway"
```

### **Logs**
```
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____
      | __  |  |  | |  |  |    \
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/

  Based on images from linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
Bubuntux: https://github.com/sponsors/bubuntux
WireGuard: https://www.wireguard.com/donations/
To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────
[2024-06-27T00:39:39+00:00] Firewall is up, everything has to go through the vpn
[2024-06-27T00:39:39+00:00] Enabling connection to eth0 172.17.0.2/16
[2024-06-27T00:39:39+00:00] Enabling connection to secure interfaces
[2024-06-27T00:39:39+00:00] Enabling connection to eth0 fe80::42:acff:fe11:2/64
[2024-06-27T00:39:39+00:00] Enabling connection to secure interfaces
[2024-06-27T00:39:39+00:00] Enabling connection to network 192.168.1.0/24
[2024-06-27T00:39:39+00:00] Enabling connection to network fdac:f190:a948::/64
Error: inet6 address is expected rather than "".
[custom-init] No custom files found, skipping...
[ls.io-init] done.
[2024-06-27T00:39:40+00:00] Finding the best server...
[2024-06-27T00:39:40+00:00] Server: {
  "id": 989159,
  "created_at": "2022-04-22 11:08:39",
  "updated_at": "2024-06-27 00:02:09",
  "name": "United States #9682",
  "station": "185.211.32.237",
  "ipv6_station": "",
  "hostname": "us9682.nordvpn.com",
  "load": 16,
  "status": "online",
  "type": "physical",
  "locations": [
    {
      "id": 77,
      "created_at": "2017-06-15 14:06:47",
      "updated_at": "2017-06-15 14:06:47",
      "latitude": 37.7698135,
      "longitude": -122.4660005,
      "country": {
        "id": 228,
        "name": "United States",
        "code": "US",
        "city": {
          "id": 8766359,
          "name": "San Francisco",
          "latitude": 37.769813,
          "longitude": -122.466001,
          "dns_name": "san-francisco",
          "hub_score": 0
        }
      }
    }
  ],
  "groups": [
    {
      "id": 11,
      "created_at": "2017-06-13 13:43:00",
      "updated_at": "2017-06-13 13:43:00",
      "title": "Standard VPN servers",
      "identifier": "legacy_standard",
      "type": {
        "id": 3,
        "created_at": "2017-06-13 13:40:17",
        "updated_at": "2017-06-13 13:40:23",
        "title": "Legacy category",
        "identifier": "legacy_group_category"
      }
    },
    {
      "id": 15,
      "created_at": "2017-06-13 13:43:38",
      "updated_at": "2017-06-13 13:43:38",
      "title": "P2P",
      "identifier": "legacy_p2p",
      "type": {
        "id": 3,
        "created_at": "2017-06-13 13:40:17",
        "updated_at": "2017-06-13 13:40:23",
        "title": "Legacy category",
        "identifier": "legacy_group_category"
      }
    },
    {
      "id": 21,
      "created_at": "2017-10-27 14:23:03",
      "updated_at": "2017-10-30 08:09:48",
      "title": "The Americas",
      "identifier": "the_americas",
      "type": {
        "id": 5,
        "created_at": "2017-10-27 14:16:30",
        "updated_at": "2017-10-27 14:16:30",
        "title": "Regions",
        "identifier": "regions"
      }
    }
  ],
  "specifications": [
    {
      "id": 8,
      "title": "Version",
      "identifier": "version",
      "values": [
        {
          "id": 257,
          "value": "2.1.0"
        }
      ]
    }
  ],
  "ips": [
    {
      "id": 682400,
      "created_at": "2022-10-19 06:10:14",
      "updated_at": "2022-10-19 06:10:14",
      "server_id": 989159,
      "ip_id": 15205775,
      "type": "entry",
      "ip": {
        "id": 15205775,
        "ip": "185.211.32.237",
        "version": 4
      }
    }
  ]
}
[2024-06-27T00:39:40+00:00] Connecting...
[#]
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.5.0.2/32 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -6 route add ::/0 dev wg0 table 51820
[#] ip -6 rule add not fwmark 51820 table 51820
[#] ip -6 rule add table main suppress_prefixlength 0
[#] ip6tables-restore -n
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] iptables-restore -n
[#]
[2024-06-27T00:39:40+00:00] Connected! \(ᵔᵕᵔ)/
```
